version: '3.7'

networks:
  docnet:
    name: outdocks
    external: true

services:
  sqlgui:
    build: .
    container_name: adminer4.7
    restart: always
    ports:
      - $SQLGUI_PORT:8080
    environment:
      # - ADMINER_DEFAULT_SERVER=database
      - ADMINER_PLUGINS=tables-filter dump-date dump-json dump-xml dump-zip
      - ADMINER_DESIGN=pepa-linha
    networks:
      docnet:
        ipv4_address: 172.30.100.100
