# to login in with this adminer to a DB like sqlite, use the password: 'admin'

up:
	@docker-compose --project-name od2 up --build -d

down:
	@docker-compose --project-name od2 down

logs:
	docker-compose --project-name od2 logs --timestamps --follow

start:
	@docker-compose --project-name od2 start

rs:
	@docker-compose --project-name od2 restart

stop:
	@docker-compose --project-name od2 stop
