version: '3.7'

networks:
  proxynet:
    name: idev
    external: true

services:
  dbpool:
    build: .
    container_name: pgbouncer
    restart: always
    ports:
      - 6432:6432
    networks:
      - proxynet
