version: '3.7'

networks:
  docnet:
    name: outdocks
    external: true

services:
  bounce01:
    build:
      context: .
      dockerfile: base.Dockerfile
    container_name: bounce01
    image: bounce01

  pool:
    build:
      context: .
      dockerfile: main.Dockerfile
    container_name: pool
    restart: always
    ports:
      - $PGBOUNCER_PORT:6432
    networks:
      docnet:
        ipv4_address: 172.30.10.10
