version: '3.7'

networks:
  proxynet:
    name: idev
    external: true

services:
  devbouncer:
    build:
      context: .
      dockerfile: base.Dockerfile
    image: devbouncer

  dbpool:
    build:
      context: .
      dockerfile: main.Dockerfile
    container_name: pgbouncer
    restart: always
    ports:
      - 6432:6432
    networks:
      - proxynet
