version: '3.7'

networks:
  docnet:
    name: outdocks
    external: true

services:
    mariadb:
      image: mariadb/server:10.5
      command: $COMMAND
      restart: always
      container_name: mariadb
      ports:
        - $MARIADB_PORT:3306
      environment:
        MYSQL_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD
        MYSQL_DATABASE: $MARIADB_DATABASE
        MYSQL_USER: $MARIADB_USER
        MYSQL_PASSWORD: $MARIADB_PASSWORD
      volumes:
        - $MARIADB_DATA:/var/lib/mysql
        - $MARIADB_CONFD:/etc/mysql/conf.d
      networks:
        docnet:
          ipv4_address: 172.30.0.5
