version: '3.7'

networks:
  proxynet:
    name: idev
    external: true

services:
  database:
    image: mariadb:10.5.3
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    container_name: mariadbv10.5.3
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: backend
      MYSQL_PASSWORD: 5ec8b1681
      MYSQL_ROOT_PASSWORD: e81bc8e51
    ports:
      - 4406:3306
    volumes:
      - $PWD/mariadbdata:/var/lib/mysql
    networks:
      - proxynet
