version: '3.7'

networks:
  docnet:
    name: outdocks
    external: true

services:
  mysqlv8:
    image: mysql:8
    restart: always
    container_name: mysqlv8
    command: $COMMAND
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_PORT:3306
    volumes:
      - $MYSQL_DATA:/var/lib/mysql
    networks:
      docnet:
        ipv4_address: 172.30.0.4