version: '3.7'

networks:
  proxynet:
    name: idev
    external: true

services:
  database:
    image: mysql:8.0.20
    restart: always
    container_name: mysqlv8.0.20
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: backend
      MYSQL_PASSWORD: 5ec8b1681
      MYSQL_ROOT_PASSWORD: e81bc8e51
    ports:
      - 3306:3306
    volumes:
      - $PWD/mysqldata:/var/lib/mysql
    networks:
      - proxynet
