version: '3.7'

networks:
  proxynet:
    name: idev
    external: true

services:
  redis:
    image: redis:6
    restart: always
    container_name: redisv6
    command: redis-server --requirepass 474ca5605719c1
    volumes:
      - $PWD/keeps/redis:/data
    ports:
      - 6369:6379
    networks:
      - proxynet
