version: '3.7'

networks:
  docnet:
    name: outdocks
    external: true

services:
  redis:
    image: redis:6.0.9-alpine
    command: $COMMAND
    container_name: redis
    restart: always
    volumes:
      - $REDIS_DATA:/data
    ports:
      - $REDIS_PORT:6379
    networks:
      docnet:
        ipv4_address: 172.30.0.3
